var xmlsegmentWinAdd;
var xmlsegmentFormAdd;
function addXmlsegment(){
	initXmlsegmentFormAdd();
	xmlsegmentWinAdd = Ext.create('Ext.Window',{
		layout:'fit',
		width:800,
		height:400,
		maximizable:true,
		minimizable:true,
		animateTarget:document.body,
		plain:true,
		modal:true,
		title:'添加信息',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:xmlsegmentFormAdd,
		buttons:[{
			text:'保存',
			itemId:'save',
			handler:function(button){
				submitForm(xmlsegmentFormAdd,'../xmlsegmentController/addXmlsegment',segmentgrid,xmlsegmentWinAdd,false,true);
			}
		},{
			text:'关闭',
			itemId:'close',
			handler:function(button){
				button.up('window').close();
			}
		}]
	});
	xmlsegmentWinAdd.show();
	
}
function initXmlsegmentFormAdd(){
	xmlsegmentFormAdd = Ext.create('Ext.FormPanel',{
		xtype:'form',
		waitMsgTarget:true,
		defaultType:'textfield',
		autoScroll:true,
		/**新方法使用开始**/
		scrollable:true,
		scrollable:'x',
		scrollable:'y',
		/**新方法使用结束**/
		fieldDefaults:{
			labelWidth:70,
			labelAlign:'left',
			flex:1,
			margin:'2 5 4 5'
		},
		items:[
		{
			fieldLabel:'信息段名称 ',
			xtype:'textfield',
			name:'segmentname',
			maxLength:50,
			anchor:'100%'
		},
		{
			fieldLabel:'信息段code',
			xtype:'textfield',
			name:'segmentcode',
			maxLength:50,
			anchor:'100%'
		},
		{
			fieldLabel:'表名',
			xtype:'textfield',
			name:'tablename',
			maxLength:40,
			anchor:'100%'
		},
		{
			fieldLabel:'模板编号',
			xtype:'textfield',
			name:'templateid',
			maxLength:40,
			anchor:'100%',
			value:templateid,
			readOnly:true
		},
		{
			fieldLabel:'属性',
			xtype:"combo",
            store:[["1","选报"],["2","必报"]],
            emptyText:"请选择",
            mode:"local",
            triggerAction:"all",
            editable:false,
            name:'property',
			hiddenName:'property',
			allowBlank:false,
			anchor:'100%'
		},
		{
			fieldLabel:'顺序',
			xtype:'numberfield',
			name:'sortno',
			maxLength:10,
			anchor:'100%'
		}
		]
	});
}
